// import "./globals.css";
// import "@/globals.css";
import "@/app/globals.css";
import { Footer, Navbar, Sidebar } from "@/components/ui";
import { ReduxProvider } from "@/redux/features/provider";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: {
    template: "Next-Level Games | %s", // %s is the page title that will be replaces with the custom title given
    default: "Next-Level Games",
  },
  description: "The official Next.js Learn Dashboard built with App Router.",
  metadataBase: new URL("https://next-learn-dashboard.vercel.sh"),
};

// export const metadata = {
//   title: "Next-Level Games",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" type="image/svg" href="../app/SiteLogo.svg" sizes="32x32" />
      </head>
      {/* <body className={`${inter.className} bg-gray-900`}> */}
      <body className={`bg-gray-900`}>
        {/* Wrapping children & layout components to have access to our REDUX STORE */}
        <ReduxProvider>
          <Navbar />
          <div className="flex">
            <Sidebar />
            <main className="container mx-auto m-6 px-2 md:px-4">{children}</main>
          </div>
          {/* <Image src={`/RacingImage.png`} fill alt="" /> */}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
