// // import LoginForm from "@/components/ui/LoginForm";

// export default function Layout({ children }: { children: React.ReactNode }) {
//   console.log("inside login layout");

//   return (
//     // <main className="bg-blue-500">
//     <html>
//       <body className="">{children}</body>
//     </html>
//     // </main>
//   );
// }

// export default function Layout({ children }: { children: React.ReactNode }) {
//   return (
//     <div className="flex h-screen flex-col md:flex-row md:overflow-hidden bg-blue-500">
//       <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
//     </div>
//   );
// }

// import "./globals.css";
// import "@/globals.css";
import "@/app/globals.css";
import { Footer, Navbar, Sidebar } from "@/components/ui";
import { ReduxProvider } from "@/redux/features/provider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "Next-Level Games | %s", // %s is the page title that will be replaces with the custom title given
    default: "Next-Level Games",
  },
  description: "The official Next.js Learn Dashboard built with App Router.",
  metadataBase: new URL("https://next-learn-dashboard.vercel.sh"),
};

// export const metadata = {
//   title: "Next-Level Games",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" type="image/svg" href="../app/SiteLogo.svg" sizes="32x32" />
      </head>
      {/* <body className={`${inter.className} bg-gray-900`}> */}
      <body className={`bg-gray-900`}>
        {/* Wrapping children & layout components to have access to our REDUX STORE */}
        {/* <ReduxProvider>
          <Navbar /> */}
        {/* <div className="flex"> */}
        {/* <Sidebar /> */}
        {/* <main className="container mx-auto m-6 px-2 md:px-4">{children}</main> */}
        <main className="flex justify-center items-center w-screen h-screen">{children}</main>
        {/* </div> */}
        {/* <Footer />
        </ReduxProvider> */}
      </body>
    </html>
  );
}
